routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('jne', function () {
    $array = array(12,43,66,21,56,43,43,78,78,100,43,43,43,21);
    $vals = array_count_values($array);
    echo 'No. of NON Duplicate Items: '.count($vals).'<br><br>';
    dd($vals);
});
// [1, 2, 3, 4, 5, 6, 7, 8, 9]

Route::get('/', function () {
	if (Auth::check()) {
		return redirect('dashboard');
	}
    return view('auth.login');
});

Route::get('moving-average', 'MovingAverageController@index');

Route::get('apriori', 'AprioriController@index');
Route::post('apriori', 'AprioriController@prosesApriori');
Route::get('process_log', 'AprioriController@process_log');
Route::get('hasil/{id}', 'AprioriController@hasil');

Route::get('kodepos', function (\App\DataTables\KodeposDataTable $dataTable) {
    return $dataTable->render('kodepos');
});

Route::get('ongkir/jx', function (\App\DataTables\JXOngkirDataTable $dataTable) {
	return $dataTable->render('jx');
});
Route::get('ongkir/jne', function () {
    $provinsi     = \App\Library\RajaOngkirLib::provinsi();
    return view('jne',compact('provinsi'));
});
Route::get('rate/jx', function () {

    $ongkir = \App\JXOngkir::all();
    foreach ($ongkir as $key => $value) {
    	$date['data'] = [
    		'items' => $value->distrisct,
    	];
    }

    return response()->json($data);
    
});

Route::get('cache',function(){
    Artisan::call('cache:clear');
    Artisan::call('view:clear');
});

Route::post('cek_kota', 'AjaxController@cekkota');
Route::post('cek_kecamatan', 'AjaxController@cekkecamatan');
Route::post('cekongkir', 'AjaxController@cekongkir');
Route::post('cek_sub', 'AjaxController@ceksub');

Auth::routes(['register' => false]);
Route::get('/dashboard', 'HomeController@dashboard')->name('dashboard');

Route::resource('order', 'OrderController');
Route::get('order/approve/{id}', 'OrderController@approve');
Route::get('order/retur/{id}', 'OrderController@retur');
Route::resource('penjualan', 'PenjualanController');
Route::get('kas/import-dana-shopee', 'KasController@import_dana_shopee')->name('kas.import-dana-shopee');
Route::post('kas/import-dana-shopee', 'KasController@post_import_dana_shopee')->name('kas.import-dana-shopee-post');
Route::resource('kas', 'KasController');
Route::resource('produk', 'ProdukController');

app/Produk.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Produk extends Model
{
    protected $table = 'produk';

    protected $fillable = [
    	'nama',
    	'kode_produk',
    	'harga_jual',
    	'harga_beli',
    ];
}

app/Http/Controllers/ProdukController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\DataTables\ProdukDataTable;
use App\Produk;

class ProdukController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(ProdukDataTable $dataTable)
    {
        return $dataTable->render('produk.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('produk.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Produk::create($request->except(['_token']));
        return redirect()->back()->with('alert-success','Berhasil menambahkan produk');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/produk/create.blade.php
@extends('layouts.app')
@section('css')

@endsection
@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            @include('include.alert')
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <form action="{{route('produk.store')}}" method="POST">
                                {{csrf_field()}}
                                <div class="form-group">
                                    <input type="text" class="form-control" name="kode_produk" placeholder="Masukan Kode Produk" required>
                                </div>
                                <div class="form-group">
                                    <input type="text" class="form-control" name="nama" placeholder="Masukan Nama Produk" required>
                                </div>
                                <div class="form-group">
                                    <input type="text" class="form-control" name="harga_beli" placeholder="Masukan Harga Beli" required>
                                </div>
                                <div class="form-group">
                                    <input type="text" class="form-control" name="harga_jual" placeholder="Masukan Harga Jual" required>
                                </div>
                                <div class="form-group">
                                    <button class="btn btn-primary">Simpan</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('js')
@endsection

resources/views/produk/index.blade.php
@extends('layouts.app')
@section('css')
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css">
@endsection
@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            {!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('js')
<script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
{!! $dataTable->scripts() !!}
@endsection