routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('jne', function () {
    $array = array(12,43,66,21,56,43,43,78,78,100,43,43,43,21);
    $vals = array_count_values($array);
    echo 'No. of NON Duplicate Items: '.count($vals).'<br><br>';
    dd($vals);
});
// [1, 2, 3, 4, 5, 6, 7, 8, 9]

Route::get('/', function () {
	if (Auth::check()) {
		return redirect('dashboard');
	}
    return view('auth.login');
});

Route::get('moving-average', 'MovingAverageController@index');

Route::get('apriori', 'AprioriController@index');
Route::post('apriori', 'AprioriController@prosesApriori');
Route::get('process_log', 'AprioriController@process_log');
Route::get('hasil/{id}', 'AprioriController@hasil');

Route::get('kodepos', function (\App\DataTables\KodeposDataTable $dataTable) {
    return $dataTable->render('kodepos');
});

Route::get('ongkir/jx', function (\App\DataTables\JXOngkirDataTable $dataTable) {
	return $dataTable->render('jx');
});
Route::get('ongkir/jne', function () {
    $provinsi     = \App\Library\RajaOngkirLib::provinsi();
    return view('jne',compact('provinsi'));
});
Route::get('rate/jx', function () {

    $ongkir = \App\JXOngkir::all();
    foreach ($ongkir as $key => $value) {
    	$date['data'] = [
    		'items' => $value->distrisct,
    	];
    }

    return response()->json($data);
    
});

Route::get('cache',function(){
    Artisan::call('cache:clear');
    Artisan::call('view:clear');
});

Route::post('cek_kota', 'AjaxController@cekkota');
Route::post('cek_kecamatan', 'AjaxController@cekkecamatan');
Route::post('cekongkir', 'AjaxController@cekongkir');
Route::post('cek_sub', 'AjaxController@ceksub');

Auth::routes(['register' => false]);
Route::get('/dashboard', 'HomeController@dashboard')->name('dashboard');

Route::resource('order', 'OrderController');
Route::get('order/approve/{id}', 'OrderController@approve');
Route::get('order/retur/{id}', 'OrderController@retur');
Route::resource('penjualan', 'PenjualanController');
Route::get('kas/import-dana-shopee', 'KasController@import_dana_shopee')->name('kas.import-dana-shopee');
Route::post('kas/import-dana-shopee', 'KasController@post_import_dana_shopee')->name('kas.import-dana-shopee-post');
Route::resource('kas', 'KasController');
Route::resource('produk', 'ProdukController');

app/Kas.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Kas extends Model
{
    protected $table = 'kas';

    protected $fillable = [
    	'tanggal',
    	'keterangan',
    	'pemasukan',
    	'pengeluaran',
    ];
}

app/Http/Controllers/KasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\DataTables\KasDataTable;
use Maatwebsite\Excel\Facades\Excel;
use App\Imports\Kas as KasImport;
use App\Imports\DanaShopee;
use App\Kas;

class KasController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(KasDataTable $dataTable)
    {
        if (empty(request()->date)) {
            return $dataTable->with(['tanggal_dari' => 'kosong'])->render('kas.index');
        }else{
            $date = explode(' - ', request()->date);
            $tanggal_dari   = $date[0];
            $tanggal_sampai = $date[1];

            $kas = Kas::whereBetween('tanggal',[$tanggal_dari,$tanggal_sampai])->get();

            return $dataTable->with(['tanggal_dari' => $tanggal_dari, 'tanggal_sampai' => $tanggal_sampai])->render('kas.index',compact('kas','tanggal_dari','tanggal_sampai'));
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('kas.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            $import  = Excel::import(new KasImport(), $request->file);
            
            return redirect()->back()->with('alert-success', 'Succes Import Data!');
        } catch (Exception $e) {
            return redirect()->back()->with('alert-danger', 'Gagal');
            
        }
    }

    public function import_dana_shopee()
    {
        return view('kas.import-shopee');
    }

    public function post_import_dana_shopee(Request $request)
    {
        try {
            $import  = Excel::import(new DanaShopee(), $request->file);
            
            return redirect()->back()->with('alert-success', 'Succes Import Data!');
        } catch (Exception $e) {
            return redirect()->back()->with('alert-danger', 'Gagal');
            
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/kas/create.blade.php
@extends('layouts.app')
@section('css')
@endsection
@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            @include('include.alert')
            <div class="card">
                <div class="card-body">
                    <div class="row mb-3">
                        <div class="col-md-12">
                            <form action="{{route('kas.store')}}" enctype="multipart/form-data" method="POST">
                                {{csrf_field()}}
                                <div class="form-group">
                                    <label for="">Upload File Excel</label>
                                    <input type="file" name="file" class="form-control" required style="padding: 3px;">
                                </div>
                                <div class="form-group">
                                    <small><i>Untuk melakukan import file excel harus mengikuti sample excel disini, download file excel <a href="{{asset('template_bukukas.xlsx')}}">disini</a></i></small>
                                </div>
                                <div class="form-group">
                                    <a href="{{route('kas.index')}}" class="btn btn-success">Kembali ke Data Kas</a>
                                    <button class="btn btn-primary">Import Data</button>
                                </div>
                            </form>  
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('js')
@endsection

resources/views/kas/import-shopee.blade.php
@extends('layouts.app')
@section('css')
@endsection
@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            @include('include.alert')
            <div class="card">
                <div class="card-body">
                    <div class="row mb-3">
                        <div class="col-md-12">
                            <form action="{{route('kas.import-dana-shopee-post')}}" enctype="multipart/form-data" method="POST">
                                {{csrf_field()}}
                                <div class="form-group">
                                    <label for="">Upload File Excel</label>
                                    <input type="file" name="file" class="form-control" required style="padding: 3px;">
                                </div>
                                <div class="form-group">
                                    <small><i>Untuk melakukan import file excel harus mengikuti sample excel disini, download file excel <a href="{{asset('template_dana_shopee.xlsx')}}">disini</a></i></small>
                                </div>
                                <div class="form-group">
                                    <a href="{{route('kas.index')}}" class="btn btn-success">Kembali ke Data Kas</a>
                                    <button class="btn btn-primary">Import Data</button>
                                </div>
                            </form>  
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('js')
@endsection

resources/views/kas/index.blade.php
@extends('layouts.app')
@section('css')
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css">
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
@endsection
@section('content')
<div class="container">
    @if(!empty(request()->date))
    <div class="row mb-2">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h5><b>Total Pemasukan</h5>
                    <small><i><b>{{$tanggal_dari}} - {{$tanggal_sampai}}</b></i></b></small>
                    <br><br>
                    <h2>Rp {{str_replace(',','.',number_format($kas->sum('pemasukan')))}}</h2>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h5><b>Total Pengeluaran</h5>
                    <small><i><b>{{$tanggal_dari}} - {{$tanggal_sampai}}</b></i></b></small>
                    <br><br>
                    <h2>Rp {{str_replace(',','.',number_format($kas->sum('pengeluaran')))}}</h2>
                </div>
            </div>
        </div>
    </div>
    @endif
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="row mb-3">
                        <div class="col-md-12">
                            <form action="" method="GET" class="form-inline">
                                <div class="form-group mr-2">
                                    <input type="text" name="date" class="form-control date" required>
                                </div>
                                <div class="form-group">
                                    <button class="btn btn-primary">Cari</button>
                                </div>
                            </form>  
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            {!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('js')
<script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
<script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
{!! $dataTable->scripts() !!}
<script>
    $('.date').daterangepicker({
        locale: {
            format: 'YYYY/MM/DD'
        }
    });
</script>
@endsection