routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('jne', function () {
    $array = array(12,43,66,21,56,43,43,78,78,100,43,43,43,21);
    $vals = array_count_values($array);
    echo 'No. of NON Duplicate Items: '.count($vals).'<br><br>';
    dd($vals);
});
// [1, 2, 3, 4, 5, 6, 7, 8, 9]

Route::get('/', function () {
	if (Auth::check()) {
		return redirect('dashboard');
	}
    return view('auth.login');
});

Route::get('moving-average', 'MovingAverageController@index');

Route::get('apriori', 'AprioriController@index');
Route::post('apriori', 'AprioriController@prosesApriori');
Route::get('process_log', 'AprioriController@process_log');
Route::get('hasil/{id}', 'AprioriController@hasil');

Route::get('kodepos', function (\App\DataTables\KodeposDataTable $dataTable) {
    return $dataTable->render('kodepos');
});

Route::get('ongkir/jx', function (\App\DataTables\JXOngkirDataTable $dataTable) {
	return $dataTable->render('jx');
});
Route::get('ongkir/jne', function () {
    $provinsi     = \App\Library\RajaOngkirLib::provinsi();
    return view('jne',compact('provinsi'));
});
Route::get('rate/jx', function () {

    $ongkir = \App\JXOngkir::all();
    foreach ($ongkir as $key => $value) {
    	$date['data'] = [
    		'items' => $value->distrisct,
    	];
    }

    return response()->json($data);
    
});

Route::get('cache',function(){
    Artisan::call('cache:clear');
    Artisan::call('view:clear');
});

Route::post('cek_kota', 'AjaxController@cekkota');
Route::post('cek_kecamatan', 'AjaxController@cekkecamatan');
Route::post('cekongkir', 'AjaxController@cekongkir');
Route::post('cek_sub', 'AjaxController@ceksub');

Auth::routes(['register' => false]);
Route::get('/dashboard', 'HomeController@dashboard')->name('dashboard');

Route::resource('order', 'OrderController');
Route::get('order/approve/{id}', 'OrderController@approve');
Route::get('order/retur/{id}', 'OrderController@retur');
Route::resource('penjualan', 'PenjualanController');
Route::get('kas/import-dana-shopee', 'KasController@import_dana_shopee')->name('kas.import-dana-shopee');
Route::post('kas/import-dana-shopee', 'KasController@post_import_dana_shopee')->name('kas.import-dana-shopee-post');
Route::resource('kas', 'KasController');
Route::resource('produk', 'ProdukController');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    @yield('css')
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    <b>{{ config('app.name', 'Laravel') }} Management</b>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item"><a class="nav-link" href="{{ url('dashboard') }}">Dashboard</a></li>
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    Order <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('order.create') }}"><i class="fa fa-plus"></i> Import Order</a>
                                    <a class="dropdown-item" href="{{ route('order.index') }}">Data Order</a>
                                </div>
                            </li>
                            {{-- <li class="nav-item"> --}}
                                {{-- <a class="nav-link" href="{{ route('order.index') }}">{{ __('Order') }}</a> --}}
                            {{-- </li> --}}
                            {{-- <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    Buku Kas <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('kas.import-dana-shopee') }}"><i class="fa fa-plus"></i> Import Dana Shopee</a>
                                    <a class="dropdown-item" href="{{ route('kas.create') }}"><i class="fa fa-plus"></i> Import Kas</a>
                                    <a class="dropdown-item" href="{{ route('kas.index') }}">Data Kas</a>
                                </div>
                            </li> --}}
                            {{-- <li class="nav-item"><a class="nav-link" href="{{ route('penjualan.index') }}">Penjualan</a></li> --}}
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    Produk <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('produk.create') }}"><i class="fa fa-plus"></i> Tambah Produk</a>
                                    <a class="dropdown-item" href="{{ route('produk.index') }}">List Produk</a>
                                </div>
                            </li>
                            {{-- <li class="nav-item"><a class="nav-link" href="{{ url('apriori') }}">Apriori</a></li> --}}
                            <li class="nav-item"><a class="nav-link" href="{{ url('moving-average') }}">Moving Average</a></li>
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
    <script src="{{ asset('js/app.js') }}"></script>
    @yield('js')

</body>
</html>